apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::619795905281:user/github_cicd
      username: github_cicd
      groups:
        - system:masters
