// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_get_book.proto

package com.bookstore.pb_gen.book_gen;

public final class PbGetBook {
  private PbGetBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bookstore.pb_gen.book_gen.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 book_id = 1;</code>
     * @return The bookId.
     */
    long getBookId();

    /**
     * <code>string book_name = 2;</code>
     * @return The bookName.
     */
    String getBookName();
    /**
     * <code>string book_name = 2;</code>
     * @return The bytes for bookName.
     */
    com.google.protobuf.ByteString
        getBookNameBytes();

    /**
     * <code>int32 stock = 3;</code>
     * @return The stock.
     */
    int getStock();

    /**
     * <code>double price = 4;</code>
     * @return The price.
     */
    double getPrice();
  }
  /**
   * Protobuf type {@code com.bookstore.pb_gen.book_gen.Book}
   */
  public static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bookstore.pb_gen.book_gen.Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      bookName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Book();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bookId_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              bookName_ = s;
              break;
            }
            case 24: {

              stock_ = input.readInt32();
              break;
            }
            case 33: {

              price_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_Book_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Book.class, Builder.class);
    }

    public static final int BOOK_ID_FIELD_NUMBER = 1;
    private long bookId_;
    /**
     * <code>int64 book_id = 1;</code>
     * @return The bookId.
     */
    @Override
    public long getBookId() {
      return bookId_;
    }

    public static final int BOOK_NAME_FIELD_NUMBER = 2;
    private volatile Object bookName_;
    /**
     * <code>string book_name = 2;</code>
     * @return The bookName.
     */
    @Override
    public String getBookName() {
      Object ref = bookName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bookName_ = s;
        return s;
      }
    }
    /**
     * <code>string book_name = 2;</code>
     * @return The bytes for bookName.
     */
    @Override
    public com.google.protobuf.ByteString
        getBookNameBytes() {
      Object ref = bookName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bookName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCK_FIELD_NUMBER = 3;
    private int stock_;
    /**
     * <code>int32 stock = 3;</code>
     * @return The stock.
     */
    @Override
    public int getStock() {
      return stock_;
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private double price_;
    /**
     * <code>double price = 4;</code>
     * @return The price.
     */
    @Override
    public double getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookId_ != 0L) {
        output.writeInt64(1, bookId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bookName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bookName_);
      }
      if (stock_ != 0) {
        output.writeInt32(3, stock_);
      }
      if (Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(4, price_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, bookId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bookName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bookName_);
      }
      if (stock_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, stock_);
      }
      if (Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Book)) {
        return super.equals(obj);
      }
      Book other = (Book) obj;

      if (getBookId()
          != other.getBookId()) return false;
      if (!getBookName()
          .equals(other.getBookName())) return false;
      if (getStock()
          != other.getStock()) return false;
      if (Double.doubleToLongBits(getPrice())
          != Double.doubleToLongBits(
              other.getPrice())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOK_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBookId());
      hash = (37 * hash) + BOOK_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getBookName().hashCode();
      hash = (37 * hash) + STOCK_FIELD_NUMBER;
      hash = (53 * hash) + getStock();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getPrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bookstore.pb_gen.book_gen.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bookstore.pb_gen.book_gen.Book)
        BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_Book_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Book.class, Builder.class);
      }

      // Construct using com.bookstore.pb_gen.book_gen.PbGetBook.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bookId_ = 0L;

        bookName_ = "";

        stock_ = 0;

        price_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_Book_descriptor;
      }

      @Override
      public Book getDefaultInstanceForType() {
        return Book.getDefaultInstance();
      }

      @Override
      public Book build() {
        Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Book buildPartial() {
        Book result = new Book(this);
        result.bookId_ = bookId_;
        result.bookName_ = bookName_;
        result.stock_ = stock_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Book) {
          return mergeFrom((Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Book other) {
        if (other == Book.getDefaultInstance()) return this;
        if (other.getBookId() != 0L) {
          setBookId(other.getBookId());
        }
        if (!other.getBookName().isEmpty()) {
          bookName_ = other.bookName_;
          onChanged();
        }
        if (other.getStock() != 0) {
          setStock(other.getStock());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long bookId_ ;
      /**
       * <code>int64 book_id = 1;</code>
       * @return The bookId.
       */
      @Override
      public long getBookId() {
        return bookId_;
      }
      /**
       * <code>int64 book_id = 1;</code>
       * @param value The bookId to set.
       * @return This builder for chaining.
       */
      public Builder setBookId(long value) {
        
        bookId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 book_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookId() {
        
        bookId_ = 0L;
        onChanged();
        return this;
      }

      private Object bookName_ = "";
      /**
       * <code>string book_name = 2;</code>
       * @return The bookName.
       */
      public String getBookName() {
        Object ref = bookName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bookName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string book_name = 2;</code>
       * @return The bytes for bookName.
       */
      public com.google.protobuf.ByteString
          getBookNameBytes() {
        Object ref = bookName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bookName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string book_name = 2;</code>
       * @param value The bookName to set.
       * @return This builder for chaining.
       */
      public Builder setBookName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bookName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string book_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookName() {
        
        bookName_ = getDefaultInstance().getBookName();
        onChanged();
        return this;
      }
      /**
       * <code>string book_name = 2;</code>
       * @param value The bytes for bookName to set.
       * @return This builder for chaining.
       */
      public Builder setBookNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bookName_ = value;
        onChanged();
        return this;
      }

      private int stock_ ;
      /**
       * <code>int32 stock = 3;</code>
       * @return The stock.
       */
      @Override
      public int getStock() {
        return stock_;
      }
      /**
       * <code>int32 stock = 3;</code>
       * @param value The stock to set.
       * @return This builder for chaining.
       */
      public Builder setStock(int value) {
        
        stock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stock = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStock() {
        
        stock_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 4;</code>
       * @return The price.
       */
      @Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 4;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bookstore.pb_gen.book_gen.Book)
    }

    // @@protoc_insertion_point(class_scope:com.bookstore.pb_gen.book_gen.Book)
    private static final Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Book();
    }

    public static Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @Override
    public Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getBookRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bookstore.pb_gen.book_gen.getBookRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 book_id = 1;</code>
     * @return The bookId.
     */
    long getBookId();
  }
  /**
   * Protobuf type {@code com.bookstore.pb_gen.book_gen.getBookRequest}
   */
  public static final class getBookRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bookstore.pb_gen.book_gen.getBookRequest)
      getBookRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getBookRequest.newBuilder() to construct.
    private getBookRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getBookRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new getBookRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getBookRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bookId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              getBookRequest.class, Builder.class);
    }

    public static final int BOOK_ID_FIELD_NUMBER = 1;
    private long bookId_;
    /**
     * <code>int64 book_id = 1;</code>
     * @return The bookId.
     */
    @Override
    public long getBookId() {
      return bookId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookId_ != 0L) {
        output.writeInt64(1, bookId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, bookId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof getBookRequest)) {
        return super.equals(obj);
      }
      getBookRequest other = (getBookRequest) obj;

      if (getBookId()
          != other.getBookId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOK_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBookId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static getBookRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static getBookRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static getBookRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static getBookRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static getBookRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static getBookRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static getBookRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static getBookRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static getBookRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static getBookRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static getBookRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static getBookRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(getBookRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bookstore.pb_gen.book_gen.getBookRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bookstore.pb_gen.book_gen.getBookRequest)
        getBookRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                getBookRequest.class, Builder.class);
      }

      // Construct using com.bookstore.pb_gen.book_gen.PbGetBook.getBookRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bookId_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_descriptor;
      }

      @Override
      public getBookRequest getDefaultInstanceForType() {
        return getBookRequest.getDefaultInstance();
      }

      @Override
      public getBookRequest build() {
        getBookRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public getBookRequest buildPartial() {
        getBookRequest result = new getBookRequest(this);
        result.bookId_ = bookId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof getBookRequest) {
          return mergeFrom((getBookRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(getBookRequest other) {
        if (other == getBookRequest.getDefaultInstance()) return this;
        if (other.getBookId() != 0L) {
          setBookId(other.getBookId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        getBookRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (getBookRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long bookId_ ;
      /**
       * <code>int64 book_id = 1;</code>
       * @return The bookId.
       */
      @Override
      public long getBookId() {
        return bookId_;
      }
      /**
       * <code>int64 book_id = 1;</code>
       * @param value The bookId to set.
       * @return This builder for chaining.
       */
      public Builder setBookId(long value) {
        
        bookId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 book_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookId() {
        
        bookId_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bookstore.pb_gen.book_gen.getBookRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bookstore.pb_gen.book_gen.getBookRequest)
    private static final getBookRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new getBookRequest();
    }

    public static getBookRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getBookRequest>
        PARSER = new com.google.protobuf.AbstractParser<getBookRequest>() {
      @Override
      public getBookRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getBookRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getBookRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<getBookRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public getBookRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getBookResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bookstore.pb_gen.book_gen.getBookResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
     * @return Whether the book field is set.
     */
    boolean hasBook();
    /**
     * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
     * @return The book.
     */
    Book getBook();
    /**
     * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
     */
    BookOrBuilder getBookOrBuilder();
  }
  /**
   * Protobuf type {@code com.bookstore.pb_gen.book_gen.getBookResponse}
   */
  public static final class getBookResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bookstore.pb_gen.book_gen.getBookResponse)
      getBookResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getBookResponse.newBuilder() to construct.
    private getBookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getBookResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new getBookResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getBookResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Book.Builder subBuilder = null;
              if (book_ != null) {
                subBuilder = book_.toBuilder();
              }
              book_ = input.readMessage(Book.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(book_);
                book_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              getBookResponse.class, Builder.class);
    }

    public static final int BOOK_FIELD_NUMBER = 1;
    private Book book_;
    /**
     * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
     * @return Whether the book field is set.
     */
    @Override
    public boolean hasBook() {
      return book_ != null;
    }
    /**
     * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
     * @return The book.
     */
    @Override
    public Book getBook() {
      return book_ == null ? Book.getDefaultInstance() : book_;
    }
    /**
     * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
     */
    @Override
    public BookOrBuilder getBookOrBuilder() {
      return getBook();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (book_ != null) {
        output.writeMessage(1, getBook());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (book_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBook());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof getBookResponse)) {
        return super.equals(obj);
      }
      getBookResponse other = (getBookResponse) obj;

      if (hasBook() != other.hasBook()) return false;
      if (hasBook()) {
        if (!getBook()
            .equals(other.getBook())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBook()) {
        hash = (37 * hash) + BOOK_FIELD_NUMBER;
        hash = (53 * hash) + getBook().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static getBookResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static getBookResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static getBookResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static getBookResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static getBookResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static getBookResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static getBookResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static getBookResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static getBookResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static getBookResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static getBookResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static getBookResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(getBookResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bookstore.pb_gen.book_gen.getBookResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bookstore.pb_gen.book_gen.getBookResponse)
        getBookResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                getBookResponse.class, Builder.class);
      }

      // Construct using com.bookstore.pb_gen.book_gen.PbGetBook.getBookResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (bookBuilder_ == null) {
          book_ = null;
        } else {
          book_ = null;
          bookBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PbGetBook.internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_descriptor;
      }

      @Override
      public getBookResponse getDefaultInstanceForType() {
        return getBookResponse.getDefaultInstance();
      }

      @Override
      public getBookResponse build() {
        getBookResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public getBookResponse buildPartial() {
        getBookResponse result = new getBookResponse(this);
        if (bookBuilder_ == null) {
          result.book_ = book_;
        } else {
          result.book_ = bookBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof getBookResponse) {
          return mergeFrom((getBookResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(getBookResponse other) {
        if (other == getBookResponse.getDefaultInstance()) return this;
        if (other.hasBook()) {
          mergeBook(other.getBook());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        getBookResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (getBookResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Book book_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Book, Book.Builder, BookOrBuilder> bookBuilder_;
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       * @return Whether the book field is set.
       */
      public boolean hasBook() {
        return bookBuilder_ != null || book_ != null;
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       * @return The book.
       */
      public Book getBook() {
        if (bookBuilder_ == null) {
          return book_ == null ? Book.getDefaultInstance() : book_;
        } else {
          return bookBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      public Builder setBook(Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          book_ = value;
          onChanged();
        } else {
          bookBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      public Builder setBook(
          Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          book_ = builderForValue.build();
          onChanged();
        } else {
          bookBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      public Builder mergeBook(Book value) {
        if (bookBuilder_ == null) {
          if (book_ != null) {
            book_ =
              Book.newBuilder(book_).mergeFrom(value).buildPartial();
          } else {
            book_ = value;
          }
          onChanged();
        } else {
          bookBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      public Builder clearBook() {
        if (bookBuilder_ == null) {
          book_ = null;
          onChanged();
        } else {
          book_ = null;
          bookBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      public Book.Builder getBookBuilder() {
        
        onChanged();
        return getBookFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      public BookOrBuilder getBookOrBuilder() {
        if (bookBuilder_ != null) {
          return bookBuilder_.getMessageOrBuilder();
        } else {
          return book_ == null ?
              Book.getDefaultInstance() : book_;
        }
      }
      /**
       * <code>.com.bookstore.pb_gen.book_gen.Book book = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Book, Book.Builder, BookOrBuilder>
          getBookFieldBuilder() {
        if (bookBuilder_ == null) {
          bookBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Book, Book.Builder, BookOrBuilder>(
                  getBook(),
                  getParentForChildren(),
                  isClean());
          book_ = null;
        }
        return bookBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bookstore.pb_gen.book_gen.getBookResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bookstore.pb_gen.book_gen.getBookResponse)
    private static final getBookResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new getBookResponse();
    }

    public static getBookResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getBookResponse>
        PARSER = new com.google.protobuf.AbstractParser<getBookResponse>() {
      @Override
      public getBookResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getBookResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getBookResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<getBookResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public getBookResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bookstore_pb_gen_book_gen_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bookstore_pb_gen_book_gen_Book_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021pb_get_book.proto\022\035com.bookstore.pb_ge" +
      "n.book_gen\"H\n\004Book\022\017\n\007book_id\030\001 \001(\003\022\021\n\tb" +
      "ook_name\030\002 \001(\t\022\r\n\005stock\030\003 \001(\005\022\r\n\005price\030\004" +
      " \001(\001\"!\n\016getBookRequest\022\017\n\007book_id\030\001 \001(\003\"" +
      "D\n\017getBookResponse\0221\n\004book\030\001 \001(\0132#.com.b" +
      "ookstore.pb_gen.book_gen.BookB\007Z\005/bookb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bookstore_pb_gen_book_gen_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bookstore_pb_gen_book_gen_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bookstore_pb_gen_book_gen_Book_descriptor,
        new String[] { "BookId", "BookName", "Stock", "Price", });
    internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bookstore_pb_gen_book_gen_getBookRequest_descriptor,
        new String[] { "BookId", });
    internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bookstore_pb_gen_book_gen_getBookResponse_descriptor,
        new String[] { "Book", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
