// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_get_book.proto

package com.bookstore.pb_gen.book_gen;

public final class ServiceGetBook {
  private ServiceGetBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026service_get_book.proto\022\035com.bookstore." +
      "pb_gen.book_gen\032\021pb_get_book.proto2y\n\013Bo" +
      "okService\022j\n\007getBook\022-.com.bookstore.pb_" +
      "gen.book_gen.getBookRequest\032..com.bookst" +
      "ore.pb_gen.book_gen.getBookResponse\"\000B\007Z" +
      "\005/bookb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PbGetBook.getDescriptor(),
        });
    PbGetBook.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
