// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Account struct {
	AccountID int64     `json:"account_id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type Book struct {
	BookID   int64  `json:"book_id"`
	BookName string `json:"book_name"`
	Stock    int32  `json:"stock"`
	// must be positive
	Price float64 `json:"price"`
}

type BookOrder struct {
	OrderID  int64  `json:"order_id"`
	UserName string `json:"user_name"`
	BookName string `json:"book_name"`
	// must be positive
	Amount  int32  `json:"amount"`
	Address string `json:"address"`
	// must be positive
	TotalPrice float64   `json:"total_price"`
	CreatedAt  time.Time `json:"created_at"`
}

type UserInfo struct {
	UserID  int64   `json:"user_id"`
	Name    string  `json:"name"`
	Address string  `json:"address"`
	Balance float64 `json:"balance"`
}
