name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: myTest
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: AppleMan922
          POSTGRES_DB: book_store
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres14
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: check all running images
        run: docker ps -a

      - name: create a new book store db
        run: docker exec postgres14 createdb --username=root --owner=root book_store

      - name: Install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
