name: Deploy to ECR

on:
  push:
    # 这个操作只会在Github
    # 收到push操作的时候发生
    branches: [main]

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Load secrets and save to app.env
        run: |
          cd grpc-order
          aws secretsmanager get-secret-value --secret-id book_store --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env
          cd ../grpc-purchase
          aws secretsmanager get-secret-value --secret-id book_store --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env
          cd ../grpc-java/userInfo-service/src/main/resources
          aws secretsmanager get-secret-value --secret-id book_store --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > application.properties
          cd ../../../../book-service/src/main/resources
          aws secretsmanager get-secret-value --secret-id book_store --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > application.properties
          cd ../../../../../

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bookstore
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo 'build book service...'
          cd grpc-java/book-service
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:book-$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:book-$IMAGE_TAG

          echo 'build userinfo service...'
          # 切换目录是跟上面连着的
          # 上边进了那个文件夹
          # 后边要退出来
          cd ../userInfo-service
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:userinfo-$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:userinfo-$IMAGE_TAG

          echo 'build order service...'
          cd ../../grpc-order
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:order-$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:order-$IMAGE_TAG

          echo 'build userinfo service...'
          cd ../grpc-purchase
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:purchase-$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:purchase-$IMAGE_TAG
